spring.application.name=springbootTest

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.encoding.force=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true


logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true
ogging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.generate-unique-name=false
spring.datasource.url=jdbc:h2:mem:testdb
